[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@raphael/gamescope-stuff"
target = "/home/bluewy/.local/bin/gamescope-stuff"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@any/steam-stuff"
target = "/home/bluewy/.local/bin/steam-stuff"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@any/proton-stuff"
target = "/home/bluewy/.local/bin/proton-stuff"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/electron-any@any/electron-flags.conf"
target = "/home/bluewy/.config/electron-flags.conf"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/scripts-any@any"
target = "/home/bluewy/.local/share/scripts"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/speech-dispatcher-any@any"
target = "/home/bluewy/.config/speech-dispatcher"

[[install_files]]
operation = "copy"
owner = "bluewy"
source = "../../../files/user-dirs-any@any/user-dirs.dirs"
target = "/home/bluewy/.config/user-dirs.dirs"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/uwsm-any@any"
target = "/home/bluewy/.config/uwsm"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/wayland-pipewire-idle-inhibit-any@any"
target = "/home/bluewy/.config/wayland-pipewire-idle-inhibit"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/xkb-any@any"
target = "/home/bluewy/.config/xkb"
