[packages.audio.service-text]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",
]

# the main thing
#
[packages]
std = [
   "plasma-meta",
   "kde-applications-meta",
   "profile-sync-daemon",
   "cachyos-firefox-settings",
]
