[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """
[device]
wifi.backend=iwd
"""
owner = "root"
target = "/etc/NetworkManager/conf.d/wifi_backend.conf"

[[spawn_files]]
content = """
[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
"""
owner = "root"
target = "/etc/resolved.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/booster-any@any/booster.yaml"
target = "/etc/booster.yaml"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.service"
target = "/etc/systemd/system/screen-off.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.fish"
target = "/usr/local/bin/screen-off.fish"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/kbd-any@any/colemak-dh-wide-custom-eu-ansi.map"
target = "/usr/share/kbd/keymaps/colemak-dh-wide-custom-eu-ansi.map"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/kbd-any@any/colemak-dh-wide-custom-eu-iso.map"
target = "/usr/share/kbd/keymaps/colemak-dh-wide-custom-eu-iso.map"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/xkb-any@any/symbols/bluewy"
target = "/usr/share/X11/xkb/symbols/bluewy"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/libinput-any@any/local-overrides.quirks"
target = "/etc/libinput/local-overrides.quirks"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/lemurs-any@sariel/config.toml"
target = "/etc/lemurs/config.toml"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/lemurs-any@sariel/lemurs-es-keymap.service"
target = "/etc/systemd/system/lemurs-es-keymap.service"
