[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/refind-any@sariel/refind.conf"
target = "/boot/EFI/refind/refind.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/refind-any@sariel/extra.conf"
target = "/boot/EFI/refind/extra.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/lenovo-battery-limit-service-any@sariel/limit-lenovo-battery"
target = "/usr/local/bin/lenovo-battery-limit"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/lenovo-battery-limit-service-any@sariel/lenovo-battery-limiter.service"
target = "/etc/systemd/system/lenovo-battery-limiter.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.service"
target = "/etc/systemd/system/screen-off.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.fish"
target = "/usr/local/bin/screen-off.fish"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/libinput-any@any/local-overrides.quirks"
target = "/etc/libinput/local-overrides.quirks"
