source = [
   "../../modules/bluewy/files/language.toml",
   "../../modules/bluewy/files/systemd-services.toml",
   "../../modules/bluewy/packages/cachyos.toml",
   "../../modules/bluewy/packages/cachyos-ignore.toml",

   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../users/elisa/packages.toml",
   "../../users/elisa/services.toml",
]
