source = [
   "../../modules/bluewy/cachyos/files.toml",
   "../../modules/bluewy/cachyos/packages.toml",
   "../../modules/bluewy/cachyos/packages-ignore.toml",
   "../../modules/bluewy/locale/files.toml",
   "../../modules/bluewy/locale/packages.toml",
   "../../modules/bluewy/systemd-xdg-autostart-generator-disable/files.toml",
   "../../modules/bluewy/lemurs/files.toml",
   "../../modules/bluewy/lemurs/packages.toml",
   "../../modules/bluewy/wireless-regdb-es-region/files.toml",
   "../../modules/bluewy/networkmanager/files.toml",
   "../../modules/bluewy/networkmanager/packages.toml",

   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../users/elisa/packages.toml",
   "../../users/elisa/services.toml",
]
