[packages]
std = [
   "amd-ucode",
   "linux-firmware",

   "linux-cachyos",
   "linux-cachyos-lts",

   # provided by chwd
   "lib32-opencl-mesa",
   "xf86-video-amdgpu",

   "btrfs-progs",

   "lact",
]
