[[services]]
enable = [
   "NetworkManager",
   "systemd-resolved",
   "bluetooth",

   "systemd-timesyncd",

   "ufw",
   "screen-off",
   "ananicy-cpp",

   "lemurs-es-keymap",
]
path = "/etc/systemd/system"
user = "root"
