[packages]
ignore = ["less", "vscodium", "glibc-eac"]

[packages.make]
std = ["rustup", "jdk21-openjdk"]

[packages.audio]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",
]

[packages.tty]
std = ["zellij", "paru", "trash-cli"]

[packages.tty.rice]
std = ["terminus-font", "fastfetch", "starship"]

[packages.tty.apps.rewrites]
std = ["eza", "fd", "ripgrep"]

[packages.tty.apps.controller]
std = ["power-profiles-daemon"]

[packages.tty.apps.network]
std = ["zerotier-one"]

[packages.tty.apps.monitoring]
std = ["bottom", "bandwhich", "nvtop"]

[packages.tty.apps.neovim]
std = [
   "neovim",
   "stylua",
   "ripgrep",
   "fzf",
   "prettier",
   "eslint_d",
   "taplo-cli",
]

[packages.tty.apps.other]
std = ["git", "downgrade"]

[packages.wayland.wm.niri]
aur = ["xwayland-satellite-git"]
# path of PKBUILD futhermore path will be the name of said package
local = ["../../aur/libastal-niri-git"]
std = ["xdg-desktop-portal-gnome", "xdg-desktop-portal-gtk"]

[packages.wayland.wm.hyprland]
std = [
   "hyprland",
   "hyprland-protocols",
   "hyprland-qtutils",

   "xdg-desktop-portal-hyprland",
   "xdg-desktop-portal-gtk",
]

[packages.wayland.apps]
aur = ["wezterm-git", "wayshot"]
std = [
   "hyprlock",
   "hypridle",
   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "pantheon-polkit-agent",
   "gnome-keyring",

   "uwsm",
   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.wayland.apps.rice]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.wayland.apps.widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
local = ["../../aur/libastal-niri-git"]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.wayland.apps.gaming]
aur = ["atlauncher-bin", "r2modman-bin", "osu-lazer-bin"]
std = [
   "steam-native-runtime",
   "heroic-games-launcher-bin",

   "umu-launcher",
   "proton-cachyos",
   "proton-ge-custom-bin",
   "protontricks",

   "gamescope",
   "mangohud",
]

[packages.wayland.apps.files]
std = [
   "nautilus",

   "vlc",
   "vlc-plugins-all",

   "loupe",
   "evince",
   "ark",
   "seahorse",
]

[packages.wayland.apps.controllers]
aur = ["overskride"]
std = ["pavucontrol", "gparted", "gnome-disk-utility"]

[packages.wayland.apps.monitor]
std = ["mission-center", "qpwgraph"]

[packages.wayland.apps.network]
std = ["localsend"]

[packages.wayland.apps.browser]
std = ["librewolf-bin", "thunderbird"]

[packages.wayland.apps.production]
aur = ["obs-pipewire-audio-capture"]
std = [
   "krita",
   "obs-studio",
   "kdenlive",
   "audacity",

   "libreoffice-fresh",
   "hunspell-es_es",
]

[packages.wayland.apps.socialmedia]
std = ["telegram-desktop"]

[packages.wayland.apps.socialmedia.discord]
aur = ["equibop-bin", "piper-tts-bin", "piper-voices-en-us"]
std = ["speech-dispatcher"]

[packages.wayland.apps.virtualization]
std = [
   "qemu-base",
   "virt-manager",
   "virt-viewer",
   "dnsmasq",
   "vde2",
   "bridge-utils",
   "openbsd-netcat",
   "spice",
   "qemu-ui-spice-app",
   "qemu-audio-spice",
   "qemu-hw-usb-redirect",
]
