daemon:
   log_level: info
   admin_groups:
      - wheel
      - sudo
   disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
   1002:731F-1DA2:E410-0000:2f:00.0:
      fan_control_enabled: true
      fan_control_settings:
         mode: curve
         static_speed: 0.5
         temperature_key: edge
         interval_ms: 500
         curve:
            40: 0.0
            45: 0.14
            60: 0.14
            70: 0.22
            75: 0.8
            80: 1.0
      pmfw_options: {}
      power_cap: 330.0
      performance_level: manual
      max_voltage: 1120
      power_profile_mode_index: 6
      power_states:
         core_clock:
            - 0
            - 1
            - 2
         memory_clock:
            - 0
            - 1
            - 2
            - 3
