# [packages.domain.env]
# :3

# tty
#
[packages.audio.service-text]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",
]

[packages.dev.lib-text]
std = ["rustup", "jdk21-openjdk"]

[packages.main.text]
ignore = ["xdg-ninja-git"]
std = ["zellij", "paru", "downgrade", "git", "less"]

[packages.main-rice.text]
std = ["terminus-font", "fastfetch", "starship"]

[packages.hardware.service-text]
std = ["power-profiles-daemon"]

[packages.hardware.text]
std = ["wiremix", "bluetui"]

[packages.hardware-monitor.text]
std = ["bottom", "bandwhich", "nvtop"]

[packages.network.service-text]
std = ["zerotier-one"]

[packages.neovim.text]
std = [
   "neovim",
   "stylua",
   "ripgrep",
   "fzf",
   "prettier",
   "eslint_d",
   "taplo-cli",
]

[packages.other.service-text]
std = ["openssh"]

# gui
#
[packages.flatpak.text-gui]
std = ["flatpak"]

[packages.waydroid.service-text-gui]
ignore = ["waydroid-image-gapps", "waydroid"]

[packages.fix.lib]
ignore = ["glibc-eac"]

[packages.niri-base.gui]
local = ["../../../aur/niri-no-systemd"]
std = [
   "xwayland-satellite",
   "xdg-desktop-portal-gnome",
   "xdg-desktop-portal-gtk",
]

[packages.niri-extra.service-text-gui]
aur = ["wayshot"]
std = [
   "hyprlock",
   "hypridle",
   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "pantheon-polkit-agent",
   "keepassxc",

   "uwsm",
   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.wezterm.lib-gui]
aur = ["wezterm-git"]
std = ["libgit2"]

[packages.rice.gui]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.ags.lib-text-gui]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   "libastal-niri-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.gaming.gui]
ignore = [
   "atlauncher-bin",
   "r2modman-bin",
   "osu-lazer-bin",
   "bettercrewlink-bin",
]
std = ["steam-native-runtime", "heroic-games-launcher-bin"]

[packages.gaming.lib-text-gui]
std = [
   "umu-launcher",
   "proton-cachyos",
   "proton-ge-custom-bin",
   "protontricks",

   "gamescope",
   "mangohud",
]

[packages.file-viewer.lib-gui]
std = ["nautilus", "vlc", "vlc-plugins-all", "loupe", "evince", "ark"]

[packages.hardware-controller.gui]
std = ["gparted"]

[packages.monitor.gui]
std = ["mission-center", "qpwgraph"]

[packages.share.gui]
std = ["localsend"]

[packages.browse.gui]
std = ["librewolf-bin", "profile-sync-daemon", "thunderbird"]

[packages.production.gui]
aur = ["obs-pipewire-audio-capture"]
ignore = ["vscodium"]
std = ["krita", "obs-studio", "kdenlive", "audacity"]

[packages.production-libreoffice.lib-gui]
std = ["libreoffice-fresh", "hunspell-es_es"]

[packages.socialmedia.gui]
std = ["telegram-desktop"]

[packages.socialmedia-discord.lib-service-gui]
aur = ["equibop-bin", "piper-tts-bin", "piper-voices-en-us"]
std = ["speech-dispatcher"]
