#!/usr/bin/env fish

# set -g UWSM_FINALIZE_VARNAMES WAYLAND_DISPLAY DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP NIRI_SOCKET
uwsm finalize WAYLAND_DISPLAY DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP NIRI_SOCKET
uwsm start niri

