[[items-install]]
operation = "copy"
owner = "bluewy"
source = "../../files/refind-any@belphegor/refind.conf"
target = "/boot/efi/refind/refind.conf"

[[items-install]]
operation = "copy"
owner = "bluewy"
source = "../../files/refind-any@belphegor/extra.conf"
target = "/boot/efi/refind/extra.conf"
