[packages.lib]
ignore = ["glibc-eac"]

[packages.make]
std = ["rustup", "jdk21-openjdk"]

[packages.audio]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",
]

[packages.tty]
ignore = ["xdg-ninja-git"]
std = ["zellij", "paru", "downgrade", "git", "less", "openssh"]

[packages.tty.rice]
std = ["terminus-font", "fastfetch", "starship"]

[packages.tty.hardware-controller]
std = ["power-profiles-daemon"]

[packages.tty.network]
std = ["zerotier-one"]

[packages.tty.monitoring]
std = ["bottom", "bandwhich", "nvtop"]

[packages.tty.neovim]
std = [
   "neovim",
   "stylua",
   "ripgrep",
   "fzf",
   "prettier",
   "eslint_d",
   "taplo-cli",
]


[packages.wayland.wm.niri]
local = ["../../../aur/niri-no-systemd"]
std = [
   "xwayland-satellite",
   "xdg-desktop-portal-gnome",
   "xdg-desktop-portal-gtk",
]

[packages.wayland.wm.niri.wezterm]
aur = ["wezterm-git"]
std = ["libgit2"]

[packages.wayland.wm.niri.extra]
aur = ["wayshot"]
std = [
   "hyprlock",
   "hypridle",
   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "pantheon-polkit-agent",
   "keepassxc",

   "uwsm",
   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.wayland.rice]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.wayland.widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   "libastal-niri-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.wayland.gaming]
ignore = [
   "atlauncher-bin",
   "r2modman-bin",
   "osu-lazer-bin",
   "bettercrewlink-bin",
]
std = [
   "steam-native-runtime",
   "heroic-games-launcher-bin",

   "umu-launcher",
   "proton-cachyos",
   "proton-ge-custom-bin",
   "protontricks",

   "gamescope",
   "mangohud",
]

[packages.wayland.files]
std = ["nautilus", "vlc", "vlc-plugins-all", "loupe", "evince", "ark"]

[packages.wayland.controllers]
aur = ["overskride"]
std = ["pavucontrol", "gparted", "gnome-disk-utility"]

[packages.wayland.monitor]
std = ["mission-center", "qpwgraph"]

[packages.wayland.network]
std = ["localsend"]

[packages.wayland.browse]
std = ["librewolf-bin", "profile-sync-daemon", "thunderbird"]

[packages.wayland.production]
aur = ["obs-pipewire-audio-capture"]
ignore = ["vscodium"]
std = ["krita", "obs-studio", "kdenlive", "audacity"]

[packages.wayland.production.libreoffice]
std = ["libreoffice-fresh", "hunspell-es_es"]

[packages.wayland.socialmedia]
std = ["telegram-desktop"]

[packages.wayland.socialmedia.discord]
aur = ["equibop-bin", "piper-tts-bin", "piper-voices-en-us"]
std = ["speech-dispatcher"]
