[[files-install]]
operation = "copy"
owner = "root"
group = "root"
source = "../../../files/rtcwake-for-mc-server-service-#gpu-nvidia/do-rtcwake-for-mc-server-#gpu-nvidia"
target = "/usr/local/bin/do-rtcwake-for-mc-server-#gpu-nvidia"

[[files-install]]
operation = "copy"
owner = "root"
group = "root"
source = "../../../files/rtcwake-for-mc-server-service-#gpu-nvidia/rtcwake-for-mc-server-#gpu-nvidia.timer"
target = "/etc/systemd/system/rtcwake-for-mc-server-#gpu-nvidia.timer"

[[files-install]]
operation = "copy"
owner = "root"
group = "root"
source = "../../../files/rtcwake-for-mc-server-service-#gpu-nvidia/rtcwake-for-mc-server-#gpu-nvidia.service"
target = "/etc/systemd/system/rtcwake-for-mc-server-#gpu-nvidia.service"
