common_packages = ["common/packages/cachyos_env.toml"]

[packages.hardware]
aur = ["acer-wmi-battery-dkms"]
std = [
   "intel-ucode",
   "linux-firmware",
   "sof-firmware",

   "linux-cachyos-nvidia-open",
   "linux-cachyos-lts-nvidia-open",
   "wireless-regdb",
   "bluez",
]

[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """
[device]
wifi.backend=iwd
"""
owner = "root"
target = "/etc/NetworkManager/conf.d/wifi_backend.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/acer_battery_limit_service/acer_battery_limit.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/acer_battery_limit_service/acer_battery_limit.fish"
target_path = "/usr/local/bin"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.fish"
target_path = "/usr/local/bin"

[services]
enable = [
   "ananicy-cpp",

   "getty@tty1",
   "acer_battery_limit",

   "NetworkManager",
   "ufw",
   "sddm",

   "screen_off",
]
