common_packages = ["common/packages/cachyos_env.toml"]

[packages]
std = [
   "amd-ucode",
   "linux-firmware",

   "linux-cachyos",
   "linux-cachyos-lts",
   "wireless-regdb",

   # TODO: add packages provided chwd
   # they might end up as being the same
   # from the desktop

   "ufw",
   "networkmanager",
   "iwd",
   "lact",
   "bluez",
   "bluez-utils",
]

[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """
[device]
wifi.backend=iwd
"""
owner = "root"
target = "/etc/NetworkManager/conf.d/wifi_backend.conf"

[[spawn_files]]
content = """
[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
"""
owner = "root"
target = "/etc/resolved.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/lenovo_battery_limit_service/lenovo_battery_limit.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/lenovo_battery_limit_service/lenovo_battery_limit.fish"
target_path = "/usr/local/bin"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.fish"
target_path = "/usr/local/bin"

[services]
enable = [
   "getty@tty1",

   "NetworkManager",
   "systemd-resolved", # this or dnsmasq

   "systemd-timesyncd",

   "ufw",
   "lenovo_battery_limit",
   "screen_off",
   "ananicy-cpp",
]

[ignore]
packages = ["sbctl"]
