# tty
#
[packages.dev.lib-text]
std = ["rustup", "jdk21-openjdk"]

[packages.main.text]
ignore = ["xdg-ninja-git"]
std = ["zellij", "paru", "downgrade", "git", "less"]

[packages.main-rice.text]
std = ["terminus-font", "fastfetch", "starship"]

[packages.hardware.lib-service-text]
std = ["power-profiles-daemon", "python-gobject"]

[packages.hardware.text]
std = ["wiremix", "bluetui"]

[packages.hardware-monitor.text]
std = ["bottom", "bandwhich", "nvtop"]

[packages.network.service-text]
std = ["zerotier-one"]

[packages.neovim.text]
std = [
   "neovim",
   "stylua",
   "ripgrep",
   "fzf",
   "prettier",
   "eslint_d",
   "taplo-cli",
]

[packages.other.service-text]
std = ["openssh"]
