[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../files/niri-any@raphael"
target = "/home/bluewy/.config/niri"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../files/hypr-any@raphael"
target = "/home/bluewy/.config/hypr"
