packages = [
   { from = "std", name = "rustup" },
   { from = "std", name = "jdk21-openjdk" },

   { from = "aur", name = "xdg-ninja-git", ignore = true },
   { from = "std", name = "zellij" },
   { from = "std", name = "paru" },
   { from = "std", name = "downgrade" },
   { from = "std", name = "git" },
   { from = "std", name = "less" },

   { from = "std", name = "terminus-font" },
   { from = "std", name = "fastfetch" },
   { from = "std", name = "starship" },

   { from = "std", name = "power-profiles-daemon" },
   { from = "std", name = "python-gobject" },

   { from = "std", name = "wiremix" },
   { from = "std", name = "bluetui" },

   { from = "std", name = "bottom" },
   { from = "std", name = "bandwhich" },
   { from = "std", name = "nvtop" },

   { from = "std", name = "zerotier-one" },

   { from = "std", name = "neovim" },
   { from = "std", name = "stylua" },
   { from = "std", name = "ripgrep" },
   { from = "std", name = "fzf" },
   { from = "std", name = "prettier" },
   { from = "std", name = "eslint_d" },
   { from = "std", name = "taplo-cli" },

   { from = "std", name = "openssh" },
]
