[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../../files/niri-any@raphael"
target = "/home/bluewy/.config/niri"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../../files/fuzzel-any@any"
target = "/home/bluewy/.config/fuzzel"
