[packages.wayland.apps.widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   "libastal-niri-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]
