[[files-spawn]]
content = """
[device]
wifi.backend=iwd
"""
owner = "root"
target = "/etc/NetworkManager/conf.d/wifi_backend.conf"

[[files-spawn]]
content = """
[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
"""
owner = "root"
target = "/etc/resolved.conf"
