[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/acer-battery-limiter.service"
target = "/etc/systemd/system/acer-battery-limiter.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/limit-acer-battery"
target = "/usr/local/bin/limit-acer-battery"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/libinput-any@any/local-overrides.quirks"
target = "/etc/libinput/local-overrides.quirks"
