[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/acer-battery-limit.service"
target = "/etc/systemd/system/acer-battery-limit.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/acer-battery-limit.fish"
target = "/usr/local/bin/acer-battery-limit.fish"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.service"
target = "/etc/systemd/system/screen-off.service"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/screen-off-service-any@any/screen-off.fish"
target = "/usr/local/bin/screen-off.fish"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../files/libinput-any@any/local-overrides.quirks"
target = "/etc/libinput/local-overrides.quirks"

