source = [
   "../../modules/cachyos/packages.toml",

   "../../modules/bluewy/files/language.toml",
   "../../modules/bluewy/packages/cachyos.toml",
   "../../modules/bluewy/packages/virtualization.toml",

   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../users/bluewy/@any/files.toml",
   "../../users/bluewy/@any/packages.toml",
   "../../users/bluewy/@any/services.toml",

   "../../users/bluewy/@raphael/files.toml",

   "../../users/elisa/files.toml",
   "../../users/elisa/packages.toml",
   "../../users/elisa/services.toml",
]
