source = [
   "../../modules/cachyos/packages.toml",
   "../../modules/cachyos-bluewy/packages.toml",
   "../../modules/language-bluewy/files.toml",

   "./packages.toml",
   "./files.toml",
   "./services.toml",

   "../../users/bluewy/@any/packages.toml",
   "../../users/bluewy/@any/files.toml",
   "../../users/bluewy/@any/services.toml",

   "../../users/bluewy/@raphael/files.toml",

   "../../users/elisa/packages.toml",
   "../../users/elisa/files.toml",
   "../../users/elisa/services.toml",
]
