include = [
   "./files.toml",
   "./packages.toml",
   "./services.toml",

   # "../../modules/for-bluewy/cachyos/files.toml",
   # "../../modules/for-bluewy/cachyos/packages.toml",
   # "../../modules/for-bluewy/cachyos/packages-ignore.toml",
   # "../../modules/for-bluewy/cachyos/services.toml",
   # "../../modules/for-bluewy/locale-iso/files.toml",
   # "../../modules/for-bluewy/locale-iso/packages.toml",
   # "../../modules/for-bluewy/systemd-xdg-autostart-generator-disable/files.toml",
   # "../../modules/for-bluewy/wireless-regdb-es-region/files.toml",
   # "../../modules/for-bluewy/wireless-regdb-es-region/packages.toml",
   # "../../modules/for-bluewy/networkmanager/files.toml",
   # "../../modules/for-bluewy/networkmanager/packages.toml",
   # "../../modules/for-bluewy/networkmanager/services.toml",
   # "../../modules/for-bluewy/bluetooth/packages.toml",
   # "../../modules/for-bluewy/bluetooth/services.toml",
   # "../../modules/for-bluewy/lemurs/files.toml",
   # "../../modules/for-bluewy/lemurs/packages.toml",
   # "../../modules/for-bluewy/lemurs/services.toml",
   #
   # "../../users/bluewy/+base/files.toml",
   # "../../users/bluewy/+base/packages.toml",
   # "../../users/bluewy/+base/services.toml",
   # "../../users/bluewy/@raphael/files.toml",
   #
   # "../../users/elisa/packages.toml",
   # "../../users/elisa/services.toml",
   #
   # "../../users/yellowy/+base-minimal/files.toml",
   # "../../users/yellowy/+base-minimal/packages.toml",
]
