[packages]
aur = ["acer-wmi-battery-dkms"]
std = [
   "intel-ucode",
   "linux-firmware",
   "sof-firmware",

   "linux-cachyos-headers",
   "linux-cachyos-nvidia-open",
   "linux-cachyos-lts-headers",
   "linux-cachyos-lts-nvidia-open",

   # provide by chwd
   "intel-gmmlib",
   "intel-media-driver",
   "lib32-opencl-nvidia",
   "libva-nvidia-driver",
   "opencl-nvidia",
   "switcheroo-control",
   "nvidia-prime",
   "nvidia-settings",
]
