[[services]]
enable = [
   # provided by chwd
   "nvidia-resume",
   "nvidia-suspend",
   "nvidia-powerd",
   "nvidia-hibernate",
   "switcheroo-control",

   "systemd-timesyncd",

   "acer-battery-limiter",
]
path = "/etc/systemd/system"
user = "root"
