[[units]]
enable = [
   "systemd-timesyncd.service",
   "acer-battery-limiter.service",

   # by chwd
   #
   "nvidia-resume.service",
   "nvidia-suspend.service",
   "nvidia-powerd.service",
   "nvidia-hibernate.service",
   "switcheroo-control.service",
]
path = "/etc/systemd/system"
user = "root"
