[[services]]
enable = [
   "getty@tty1",

   # provided by chwd
   "nvidia-resume",
   "nvidia-suspend",
   "nvidia-powerd",
   "nvidia-hibernate",
   "switcheroo-control",

   "NetworkManager",
   "systemd-resolved", # this or dnsmasq

   "systemd-timesyncd",

   "bluetooth",

   "ufw",
   "acer-battery-limit",
   "screen-off",
   "ananicy-cpp",
]
path = "/etc/systemd/system"
user = "root"
