[[spawn_files]]
content = """
LANG=en_IE.UTF-8
LC_ADDRESS=en_IE.UTF-8
LC_IDENTIFICATION=en_IE.UTF-8
LC_MEASUREMENT=en_IE.UTF-8
LC_MONETARY=en_IE.UTF-8
LC_NAME=en_IE.UTF-8
LC_NUMERIC=en_IE.UTF-8
LC_PAPER=en_IE.UTF-8
LC_TELEPHONE=en_IE.UTF-8
LC_TIME=en_IE.UTF-8
"""
owner = "root"
target = "/etc/locale.conf"

[[spawn_files]]
# en_US is here for compatability reasons (ehem steam)
content = """
en_IE.UTF-8 UTF-8
en_US.UTF-8 UTF-8
"""
owner = "root"
target = "/etc/locale.gen"

[[spawn_files]]
content = """
XKBLAYOUT=bluewy
FONT=ter-124n
XKBMODEL=colemak-dh-wide-custom-eu-iso
KEYMAP=colemak-dh-wide-custom-eu-iso
"""
owner = "root"
target = "/etc/vconsole.conf"
