common_packages = ["common/packages/cachyos_env.toml"]

[packages]
std = [
   "amd-ucode",
   "linux-firmware",

   "linux-cachyos",
   "linux-cachyos-lts",
   "wireless-regdb",

   "lib32-opencl-mesa",
   "xf86-video-amdgpu",

   "lact",
   "bluez",
]

[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """
[Match]
Name=eno1

[Network]
DHCP=yes

[DHCPv4]
RouteMetric=100

[IPv6AcceptRA]
RouteMetric=100
"""
owner = "root"
target = "/etc/systemd/network/20-wired.network"

[[spawn_files]]
content = """
[Match]
Name=wlan0

[Network]
DHCP=yes

[DHCPv4]
RouteMetric=600

[IPv6AcceptRA]
RouteMetric=600
"""
owner = "root"
target = "/etc/systemd/network/21-wireless.network"

[services]
enable = [
   "ananicy-cpp",
   "getty@tty1",

   "systemd-networkd",
   "systemd-network-generator",
   "systemd-networkd-wait-online",

   "systemd-resolved",

   "lactd",
   "ufw",
]
