[packages.progamming_languages]
std = ["rustup", "jdk21-openjdk"]

[packages.fix]
std = [
   # fixes easy anticheat (bug introduced as a result of missing compile options)
   "glibc-eac",
]

[packages.utilities]
std = [
   "git",

   #  monitoring
   "bottom",
   "bandwhich",
   "nvtop",

   # rust rewrites
   "eza",
   "fd",
   "ripgrep",
]

[packages.utilities_nvim]
aur = ["fish-lsp-git"]
std = ["neovim", "stylua", "ripgrep", "fzf", "prettier", "eslint_d"]

[packages.tty_session]
std = [
   "zellij",
   
   # ricing
   "terminus-font", # larger font size
   "figlet",
   "fastfetch",
]

[packages.hyprland_session]
aur = [
   # stable version is broken on arch linux
   "wezterm-git",
   "wayshot",
]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",

   "hyprland",
   "hyprland-protocols",
   "hyprland-qtutils",
   "hyprpolkitagent",

   "xdg-desktop-portal-hyprland",
   "xdg-desktop-portal-gtk",

   "hyprlock",
   "hypridle",

   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "kwalletmanager",
   "kwallet",
   "kwallet-pam",
   "ksshaskpass",

   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.hyprland_widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.hyprland_rice]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.apps]
std = [
   # hardware controllers
   "pavucontrol",
   "gparted",
   "gnome-disk-utility",
   "power-profiles-daemon",

   # browsing :3
   "librewolf-bin",
   "thunderbird",

   # file manager
   "archlinux-xdg-menu",
   "dolphin",

   # file viewers
   "vlc",
   "loupe",
   "evince",
   "ark",

   # monitoring
   "mission-center",
   "qpwgraph",

   # production
   "krita",
   "obs-studio",
   "kdenlive",
   "audacity",

   "libreoffice-fresh",
   "hunspell-es_es",


   # gaming
   "steam-native-runtime",
   "heroic-games-launcher-bin",

   "umu-launcher",
   "proton-ge-custom-bin",
   "gamescope",
   "protontricks",
   "mangohud",

   # other
   "localsend",
]

[packages.apps_discord]
aur = ["equibop-bin"]
std = ["speech-dispatcher"]

[packages.virtualization]
std = [
   "qemu-base",
   "virt-manager",
   "virt-viewer",
   "dnsmasq",
   "vde2",
   "bridge-utils",
   "openbsd-netcat",
   "spice",
   "qemu-ui-spice-app",
   "qemu-audio-spice",
   "qemu-hw-usb-redirect",
]

[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """\
   [Match]
   Name=eno1
   [Network]
   DHCP=yes
   [DHCPv4]
   RouteMetric=100
   [IPv6AcceptRA]
   RouteMetric=100
"""
owner = "root"
target = "/etc/systemd/network/20-wired.network"
