#!/usr/bin/env fish

set -l script_dir (realpath (dirname (status filename)))
set -l cachy_browser_overrides_file "$script_dir/src/cachy.overrides.cfg"
set -l cachy_browser_css_file "$script_dir/src/userChrome.css"

mkdir -p "$HOME/.cachy"

ln -sf "$cachy_browser_overrides_file" "$HOME/.cachy/cachy.overrides.cfg"

set -l target_dirs (find "$HOME/.cachy" -type d -name '*default-release' 2>/dev/null)

for dir in $target_dirs
    set -l chrome_dir "$dir/chrome"

    if not test -d "$chrome_dir"
        mkdir -p "$chrome_dir"
    end

    ln -sf "$cachy_browser_css_file" "$chrome_dir/userChrome.css"
end
