[packages.development_dependencies]
std = [
   "rustup",
   "taplo-cli", # toml formatting

   # separator
   "jdk21-openjdk",
]

[packages.fix]
aur = [
   # fixes easy anticheat (bug introduced as a result of missing compile options)
   "glibc-eac",
]

[packages.utilities]
std = [

   #  monitoring
   "bottom",
   "bandwhich",
   "nvtop",

   # rust rewrites
   "eza",
   "fd",
   "ripgrep",

   # other
   "git",
   "downgrade",
]

[packages.utilities_nvim]
aur = ["fish-lsp-git"]
std = ["neovim", "stylua", "ripgrep", "fzf", "prettier", "eslint_d"]

[packages.tty_session]
std = [
   "zellij",

   # ricing
   "terminus-font", # larger font size
   "figlet",
   "fastfetch",
]

[packages.hyprland_session]
aur = [
   # stable version is broken on arch linux
   "wezterm-git",
   "wayshot",
]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",

   "hyprland",
   "hyprland-protocols",
   "hyprland-qtutils",
   "hyprpolkitagent",

   "xdg-desktop-portal-hyprland",
   "xdg-desktop-portal-gtk",

   "hyprlock",
   "hypridle",

   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "kwalletmanager",
   "kwallet",
   "kwallet-pam",
   "ksshaskpass",

   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.hyprland_widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.hyprland_rice]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.apps]
aur = [
   # part of obs
   "obs-pipewire-audio-capture",

   # harware controllers
   "overskride",
]
std = [
   # hardware controllers
   "pavucontrol",
   "gparted",
   "gnome-disk-utility",
   "power-profiles-daemon",

   # browsing :3
   "librewolf-bin",
   "thunderbird",

   # file manager
   "archlinux-xdg-menu",
   "dolphin",

   # file viewers
   "vlc",
   "vlc-plugins-all",

   "loupe",
   "evince",
   "ark",
   "seahorse",

   # monitoring
   "mission-center",
   "qpwgraph",

   # production
   "krita",
   "obs-studio",
   "kdenlive",
   "audacity",

   "libreoffice-fresh",
   "hunspell-es_es",

   # gaming
   "steam-native-runtime",
   "heroic-games-launcher-bin",

   "umu-launcher",
   "proton-ge-custom-bin",
   "gamescope",
   "protontricks",
   "mangohud",

   # communication
   "telegram-desktop",

   # other
   "localsend",
   "zerotier-one",
]

[packages.apps_discord]
aur = ["equibop-bin"]
std = ["speech-dispatcher"]

[packages.virtualization]
std = [
   "qemu-base",
   "virt-manager",
   "virt-viewer",
   "dnsmasq",
   "vde2",
   "bridge-utils",
   "openbsd-netcat",
   "spice",
   "qemu-ui-spice-app",
   "qemu-audio-spice",
   "qemu-hw-usb-redirect",
]

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/ags"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/ags2"
target_path = "/home/bluewy/.config"

[[install_files]]
operation="link"
owner="bluewy"
source = "common/files/applications/obs.desktop"
target_path = "/home/bluewy/.local/share/applications"

[[install_files]]
operation="link"
owner="bluewy"
source = "common/files/applications/steam-native.desktop"
target_path = "/home/bluewy/.local/share/applications"

# [[install_files]]
# operation = "link"
# owner = "bluewy"
# source = "common/files/applications/*"
# target_path = "/home/bluewy/.local/share/applications"
#
# [[install_files]]
# operation = "link"
# owner = "bluewy"
# source = "common/files/bin/*"
# target_path = "/home/bluewy/.local/bin"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/css"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/electron_flags/electron-flags.conf"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fastfetch"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fish_bluewy"
target_path = "/home/bluewy/.config"

[[spawn_files]]
content = """
source /home/bluewy/.config/fish_bluewy/config.fish
"""
owner = "bluewy"
target = "/home/bluewy/.config/fish/conf.d/init_bluewy.fish"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fuzzel"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/hypr"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/kbd/colemak_dh_wide_custom_eu_ansi.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/kbd/colemak_dh_wide_custom_eu_iso.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/kde/kdeglobals"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/libinput/local-overrides.quirks"
target_path = "/etc/libinput"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/librewolf/librewolf.overrides.cfg"
target_path = "/home/bluewy/.librewolf"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/mangohud"
target_name = "MangoHud"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/nvim"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/pipewire"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/speech-dispatcher"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/user-dirs.dirs/user-dirs.dirs"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/wayland-pipewire-idle-inhibit"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/wezterm"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/xkb/symbols/bluewy"
target_path = "/usr/share/X11/xkb/symbols"
