[ignore]
packages = ["libastal-niri-git"]

[packages.make]
std = ["rustup", "jdk21-openjdk"]

[packages.fix]
aur = ["glibc-eac"]

[packages.audio]
std = [
   "wireplumber",
   "pipewire",
   "pipewire-alsa",
   "pipewire-pulse",
   "pipewire-jack",
]

[packages.tty]
std = ["zellij"]

[packages.tty.rice]
std = ["terminus-font", "figlet", "fastfetch"]

[packages.tty.apps.rewrites]
std = ["eza", "fd", "ripgrep"]

[packages.tty.apps.controller]
std = ["power-profiles-daemon"]

[packages.tty.apps.network]
std = ["zerotier-one"]

[packages.tty.apps.monitoring]
std = ["bottom", "bandwhich", "nvtop"]

[packages.tty.apps.neovim]
aur = ["fish-lsp-git"]
std = [
   "neovim",
   "stylua",
   "ripgrep",
   "fzf",
   "prettier",
   "eslint_d",
   "taplo-cli",
]

[packages.tty.apps.other]
std = ["git", "downgrade"]

[packages.wayland.wm.niri]
aur = ["xwayland-satellite-git"]
# path of PKBUILD futhermore path will be the name of said package
local_paths = ["common/aur/niri-no-systemd-git"]
std = ["xdg-desktop-portal-gnome"]

[packages.wayland.wm.hyprland]
std = [
   "hyprland",
   "hyprland-protocols",
   "hyprland-qtutils",

   "xdg-desktop-portal-hyprland",
   "xdg-desktop-portal-gtk",
]

[packages.wayland.apps]
aur = ["wezterm-git", "wayshot"]
std = [
   "hyprlock",
   "hypridle",
   "hyprpicker",
   "wayland-pipewire-idle-inhibit",

   "polkit-gnome",
   "gnome-keyring",

   "uwsm",
   "fuzzel",
   "slurp",
   "satty",

   "cliphist",
]

[packages.wayland.apps.rice]
aur = [
   "qt6ct-kde",
   "qt5ct-kde",
   "bibata-cursor-theme-bin",
   "candy-icons-git",
   "sweet-folders-icons-git",
]
std = [
   "font-manager",
   "ttf-iosevkaterm-nerd",

   "kvantum",
   "kvantum-qt5",

   "nwg-look",
]

[packages.wayland.apps.widgets]
aur = [
   "libastal-io-git",
   "libastal-git",
   "libastal-4-git",
   "libastal-gjs-git",
   "libastal-hyprland-git",
   "libastal-battery-git",
   "libastal-notifd-git",
   "libastal-wireplumber-git",
   "libastal-apps-git",
   "libastal-powerprofiles-git",
   "libastal-tray-git",

   # gnim bindings are provided by the following package
   "aylurs-gtk-shell-git",
]
std = ["dart-sass", "fd", "bun-bin", "gjs", "gtk4-layer-shell"]

[packages.wayland.apps.gaming]
std = [
   "steam-native-runtime",
   "heroic-games-launcher-bin",

   "umu-launcher",
   "proton-ge-custom-bin",
   "gamescope",
   "protontricks",
   "mangohud",
]

aur = ["atlauncher-bin", "r2modman-bin", "osu-lazer-bin"]


[packages.wayland.apps.files]
std = [
   "archlinux-xdg-menu",
   "dolphin",

   "vlc",
   "vlc-plugins-all",

   "loupe",
   "evince",
   "ark",
   "seahorse",
]

[packages.wayland.apps.controllers]
std = ["pavucontrol", "gparted", "gnome-disk-utility", "overskride"]

[packages.wayland.apps.monitor]
std = ["mission-center", "qpwgraph"]

[packages.wayland.apps.network]
std = ["localsend"]

[packages.wayland.apps.browser]
std = ["librewolf-bin", "thunderbird"]

[packages.wayland.apps.production]
aur = ["obs-pipewire-audio-capture"]
std = [
   "krita",
   "obs-studio",
   "kdenlive",
   "audacity",

   "libreoffice-fresh",
   "hunspell-es_es",
]

[packages.wayland.apps.socialmedia]
std = ["telegram-desktop"]

[packages.wayland.apps.socialmedia.discord]
aur = ["equibop-bin", "piper-tts-bin", "piper-voices-en-us"]
std = ["speech-dispatcher"]

[packages.wayland.apps.virtualization]
std = [
   "qemu-base",
   "virt-manager",
   "virt-viewer",
   "dnsmasq",
   "vde2",
   "bridge-utils",
   "openbsd-netcat",
   "spice",
   "qemu-ui-spice-app",
   "qemu-audio-spice",
   "qemu-hw-usb-redirect",
]

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/ags"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/ags2"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/applications/obs.desktop"
target_path = "/home/bluewy/.local/share/applications"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/applications/steam-native.desktop"
target_path = "/home/bluewy/.local/share/applications"

# [[install_files]]
# operation = "link"
# owner = "bluewy"
# source = "common/files/applications/*"
# target_path = "/home/bluewy/.local/share/applications"
#
# [[install_files]]
# operation = "link"
# owner = "bluewy"
# source = "common/files/bin/*"
# target_path = "/home/bluewy/.local/bin"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/css"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/electron_flags/electron-flags.conf"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fastfetch"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fish_bluewy"
target_path = "/home/bluewy/.config"

[[spawn_files]]
content = """
source /home/bluewy/.config/fish_bluewy/config.fish
"""
owner = "bluewy"
target = "/home/bluewy/.config/fish/conf.d/init_bluewy.fish"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/fuzzel"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/hypr"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/kbd/colemak_dh_wide_custom_eu_ansi.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/kbd/colemak_dh_wide_custom_eu_iso.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/kde/kdeglobals"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/libinput/local-overrides.quirks"
target_path = "/etc/libinput"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/librewolf/librewolf.overrides.cfg"
target_path = "/home/bluewy/.librewolf"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/mangohud"
target_name = "MangoHud"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/niri"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/nvim"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/pipewire"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/scripts"
target_path = "/home/bluewy/.local/scripts"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/speech-dispatcher"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/user-dirs.dirs/user-dirs.dirs"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/wayland-pipewire-idle-inhibit"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "common/files/wezterm"
target_path = "/home/bluewy/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/xkb/symbols/bluewy"
target_path = "/usr/share/X11/xkb/symbols"
