[[spawn_files]]
content = "WIRELESS_REGDOM=\"ES\""
owner = "root"
target = "/etc/conf.d/wireless-regdom"

[[spawn_files]]
content = """
[device]
wifi.backend=iwd
"""
owner = "root"
target = "/etc/NetworkManager/conf.d/wifi_backend.conf"

[[spawn_files]]
content = """
[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
"""
owner = "root"
target = "/etc/resolved.conf"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/acer_battery_limit_service/acer_battery_limit.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/acer_battery_limit_service/acer_battery_limit.fish"
target_path = "/usr/local/bin"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.service"
target_path = "/etc/systemd/system"

[[install_files]]
operation = "copy"
owner = "root"
source = "common/files/screen_off_service/screen_off.fish"
target_path = "/usr/local/bin"

