#!/usr/bin/env fish

# part 1
set init_file $HOME/.config/fish/conf.d/init_bluewy.fish

if test -f $init_file
    rm $init_file
end

mkdir -p (dirname $init_file)
touch $init_file

echo "source $HOME/.config/fish_bluewy/config.fish" >$init_file

# part 2
set src_theme_file (realpath (dirname (status filename)))/custom/fish_bluewy/themes/one_dark_custom.theme
set target_theme_file $HOME/.config/fish/themes/one_dark_custom.theme

if test -f $target_theme_file -o -L $target_theme_file
    rm $target_theme_file; or unlink $target_theme_file
end

mkdir -p (dirname $target_theme_file)
ln -s $src_theme_file $HOME/.config/fish/themes
