#!/usr/bin/env fish

set init_file $HOME/.config/fish/conf.d/init_bluewy.fish

if test -f $init_file
    rm $init_file
end

mkdir -p (dirname $init_file)
touch $init_file

echo "source $HOME/.config/fish_bluewy/config.fish" >$init_file
