"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:surface_container)\
$time\
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
[ ](fg:surface_container)\
$line_break\
$character"""

palette = 'onedark'

[time]
disabled = false
time_format = "%R"
style = "bg:surface_container"
format = """
[[ $time ](fg:on_surface_container bg:surface_container)]($style)\
"""

[username]
show_always = true
style_user = "bg:surface_container fg:on_surface_container"
style_root = "bg:surface_container fg:on_surface_container"
format = """
[](bg:surface_container fg:on_surface_container)\
[ $user ]($style)\
"""

[directory]
style = "bg:surface_container fg:on_surface_container"
truncation_length = 3
truncation_symbol = "…/"
format = """
[](bg:surface_container fg:on_surface_container)\
[ $path ]($style)\
"""

[git_branch]
symbol = ""
style = "bg:surface_container"
format = """
[](bg:surface_container fg:on_surface_container)\
[[$symbol $branch ](fg:on_surface_container bg:surface_container)]($style)\
"""

[git_status]
style = "bg:surface_container"
format = """
([](bg:surface_container fg:on_surface_container)\
[[ ($all_status$ahead_behind) ](fg:on_surface_container bg:surface_container)]($style))\
"""

[cmd_duration]
show_milliseconds = true
format = """
[](bg:surface_container fg:on_surface_container)\
[ $duration ](bg:surface_container fg:on_surface_container)\
"""
style = "bg:surface_container"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
# vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
# vimcmd_replace_symbol = '[❮](bold fg:lavender)'
# vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.onedark]
surface_container = "#282C34"
on_surface_container = "#ABB2BF"
green = "#98c379"
red = "#f44747"
