[[install_files]]
operation = "link"
owner = "elisa"
source = "../../../../common/files/applications/steam-native.desktop"
target_path = "/home/elisa/.local/share/applications"

[[install_files]]
operation = "link"
owner = "elisa"
source = "../../../../common/files/bin/gamescope-stuff"
target_path = "/home/elisa/.local/bin"

[[install_files]]
operation = "link"
owner = "elisa"
source = "../../../../common/files/bin/steam-stuff"
target_path = "/home/elisa/.local/bin"

[[install_files]]
operation = "link"
owner = "elisa"
source = "../../../../common/files/bin/proton-stuff"
target_path = "/home/elisa/.local/bin"
