version: 2
daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:731F-1DA2:E410-0000:03:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: junction
      interval_ms: 500
      curve:
        44: 0.0
        45: 0.13
        50: 0.13
        55: 0.25
        70: 0.5
        80: 1.0
      spindown_delay_ms: 3000
      change_threshold: 3
    power_cap: 330.0
    performance_level: manual
    max_voltage: 1120
    power_profile_mode_index: 1
    power_states:
      memory_clock:
      - 0
      - 1
      - 2
      - 3
      core_clock:
      - 0
      - 1
      - 2
current_profile: null
auto_switch_profiles: false
