[packages]
std = [
   "base",
   "base-devel",

   "booster",
   "refind",

   "nushell",
   "fish",

   "cachyos-hooks",
   "cachyos-keyring",
   "cachyos-mirrorlist",
   "cachyos-rate-mirrors",
   "cachyos-v3-mirrorlist",
   "cachyos-v4-mirrorlist",
   "cachyos-settings",
   "chwd",

   "wireless-regdb",
   "ufw",
]
