source = [
   "../../modules/cachyos/packages.toml",

   "./packages.toml",
   "./files.toml",
   "./services.toml",

   "../../home/bluewy/@any/packages.toml",
   "../../home/bluewy/@any/files.toml",
   "../../home/bluewy/@raphael/files.toml",
]
