source = [
   "../../modules/for-bluewy/cachyos/files.toml",
   "../../modules/for-bluewy/cachyos/packages.toml",
   "../../modules/for-bluewy/cachyos/packages-ignore.toml",
   "../../modules/for-bluewy/cachyos/services.toml",
   "../../modules/for-bluewy/locale/files.toml",
   "../../modules/for-bluewy/locale/packages.toml",
   "../../modules/for-bluewy/systemd-xdg-autostart-generator-disable/files.toml",
   "../../modules/for-bluewy/wireless-regdb-es-region/files.toml",
   "../../modules/for-bluewy/wireless-regdb-es-region/packages.toml",
   "../../modules/for-bluewy/bluetooth/packages.toml",
   "../../modules/for-bluewy/bluetooth/services.toml",

   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../users/bluewy/+base/files.toml",
   "../../users/bluewy/+base/packages.toml",
   "../../users/bluewy/+base/services.toml",
   "../../users/bluewy/@raphael/files.toml",
]
