source = [
   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../modules/cachyos/files.toml",
   "../../modules/cachyos/packages.toml",
   "../../modules/cachyos/packages-ignore.toml",
   "../../modules/cachyos/services.toml",
   "../../modules/locale/files.toml",
   "../../modules/locale/packages.toml",
   "../../modules/systemd-xdg-autostart-generator-disable/files.toml",
   "../../modules/wireless-regdb-es-region/files.toml",
   "../../modules/bluetooth/packages.toml",
   "../../modules/bluetooth/services.toml",


   "../../users/bluewy/hosts/any/index.toml",
   "../../users/bluewy/hosts/raphael/files.toml",
]
