source = [
   "../../modules/bluewy/cachyos/files.toml",
   "../../modules/bluewy/cachyos/packages.toml",
   "../../modules/bluewy/cachyos/packages-ignore.toml",
   "../../modules/bluewy/cachyos/services.toml",
   "../../modules/bluewy/locale/files.toml",
   "../../modules/bluewy/locale/packages.toml",
   "../../modules/bluewy/systemd-xdg-autostart-generator-disable/files.toml",
   "../../modules/bluewy/wireless-regdb-es-region/files.toml",
   "../../modules/bluewy/bluetooth/packages.toml",
   "../../modules/bluewy/bluetooth/services.toml",
   "../../modules/bluewy/lemurs/files.toml",
   "../../modules/bluewy/lemurs/packages.toml",

   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../users/bluewy/@any/files.toml",
   "../../users/bluewy/@any/packages.toml",
   "../../users/bluewy/@any/services.toml",
   "../../users/bluewy/@raphael/files.toml",
]
