packages = [
   { from = "std", name = "linux-firmware" },
   { from = "std", name = "amd-ucode" },

   { from = "std", name = "linux-cachyos" },
   { from = "std", name = "linux-cachyos-lts" },

   { from = "std", name = "btrfs-progs" },

   { from = "std", name = "iwd" },

   { from = "std", name = "lact" },

   # by chwd
   #
   { from = "std", name = "lib32-opencl-mesa" },
   { from = "std", name = "xf86-video-amdgpu" },
]
