[[services]]
enable = [
   "getty@tty1",

   "systemd-networkd",
   "systemd-network-generator",
   "systemd-networkd-wait-online",
   "systemd-resolved",
   "iwd",

   "systemd-timesyncd",

   "lactd",
]
path = "/etc/systemd/system"
user = "root"
