[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/fastfetch-any@any"
target = "/home/bluewy/.config/fastfetch"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/nushell-any@any"
target = "/home/bluewy/.config/nushell"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/nvim-any@any"
target = "/home/bluewy/.config/nvim"

[[install_files]]
operation = "link"
owner = "bluewy"
source = "../../../files/starship-any@any/starship.toml"
target = "/home/bluewy/.config/starship.toml"

[[install_files]]
operation = "copy"
owner = "bluewy"
source = "../../../files/user-dirs-any@any/user-dirs.dirs"
target = "/home/bluewy/.config/user-dirs.dirs"
