[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/ags2"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/electron_flags/electron-flags.conf"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/fastfetch"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/fuzzel"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../../../common/files/kbd/colemak_dh_wide_custom_eu_ansi.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "copy"
owner = "root"
source = "../../../../common/files/kbd/colemak_dh_wide_custom_eu_iso.map"
target_path = "/usr/share/kbd/keymaps"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/librewolf/librewolf.overrides.cfg"
target_path = "/home/blacky/.librewolf"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../files/niri"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/nushell"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/nvim"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/scripts"
target_path = "/home/blacky/.local/scripts"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/starship/starship.toml"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "copy"
owner = "blacky"
source = "../../../../common/files/user-dirs.dirs/user-dirs.dirs"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/wayland-pipewire-idle-inhibit"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/wezterm"
target_path = "/home/blacky/.config"

[[install_files]]
operation = "link"
owner = "blacky"
source = "../../../../common/files/xkb/symbols/bluewy"
target_path = "/home/blacky/.config/xkb/symbols"
