[packages]
ignore = ["sbctl", "linux-cachyos-rc", "btrfs-assitant"]
std = [
   "amd-ucode",
   "linux-firmware",

   "linux-cachyos",
   "linux-cachyos-lts",
   "wireless-regdb",

   # provided by chwd
   "lib32-opencl-mesa",
   "xf86-video-amdgpu",

   "ufw",
   "lact",
   "bluez",
   "bluez-utils",
]
